# Generated by Django 2.1.7 on 2019-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDG_M_documentDetails',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fileurl', models.URLField(max_length=500)),
                ('Metadata', models.CharField(max_length=2000)),
                ('Hash', models.CharField(max_length=2000)),
                ('delimeter', models.CharField(max_length=200)),
                ('VGuid', models.CharField(max_length=200)),
                ('VPage', models.IntegerField(default=0)),
                ('CustomeID', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('Modified_on', models.DateTimeField(auto_now=True)),
                ('Created_by', models.IntegerField(default=0)),
                ('Modified_by', models.IntegerField(default=0)),
                ('ExcelId', models.IntegerField(default=0)),
            ],
        ),
    ]
