# Generated by Django 2.1.7 on 2019-02-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDG_M_ExcelDetails',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Filename', models.CharField(max_length=2000)),
                ('extention', models.CharField(max_length=200)),
                ('publicGuid', models.CharField(max_length=200)),
                ('Customer_ID', models.IntegerField(default=0)),
                ('Filepath', models.CharField(max_length=200)),
                ('progressStatus', models.IntegerField(default=0)),
            ],
        ),
    ]
